<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-326V1L9" failures="1" tests="5" name="AddNewPayee" time="7.02" errors="0" timestamp="2019-11-30T23:50:55 IST">
  <testcase classname="tests.AddNewPayee" name="addNewPayee" time="0.744"/>
  <testcase classname="tests.AddNewPayee" name="addNewPayee" time="0.1"/>
  <testcase classname="tests.AddNewPayee" name="addNewPayee" time="0.104"/>
  <testcase classname="tests.AddNewPayee" name="addNewPayee" time="0.088"/>
  <testcase classname="tests.AddNewPayee" name="test02" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at tests.AddNewPayee.test02(AddNewPayee.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test02 -->
</testsuite> <!-- AddNewPayee -->
